<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_model');
    } 

    /*
     * Listing of admin
     */
    function index()
    {
        $data['admin'] = $this->Admin_model->get_all_admin();
        
        $data['main_view'] = 'admin/index';
        $this->load->view('template', $data);

            }

    /*
     * Adding a new admin
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'nama' => $this->input->post('nama'),
                'alamat' => $this->input->post('alamat'),
				'pass' => $this->input->post('pass'),
				'uname' => $this->input->post('uname'),
				'class' => $this->input->post('class'),
                'status' => $this->input->post('status'),
            );
            
            $params1 = array(
                'nama' => $this->input->post('nama'),
                'alamat' => $this->input->post('alamat'),
                
            );            
             
            $this->session->set_flashdata('announce', 'Berhasil Tambah Data');
            $admin_id = $this->Admin_model->add_admin($params);
             $this->Admin_model->add_pelanggan($params1);

            redirect('admin/index');
        }
        else
        {            
            $data['main_view'] = 'admin/add';
            $this->load->view('template',$data);
        }
    }  

    /*
     * Editing a admin
     */
    function edit()
    {   
        // check if the admin exists before trying to edit it
                $id=$_GET['id'];
                $r=$_GET['r'];
                $params = array(
					'status' => $r,
					
                );

                $this->session->set_flashdata('announce', 'Berhasil Ubah Data');
                $this->Admin_model->update_admin($id,$params);            
                redirect('admin/index');
            
    } 
    function update($id)
    {   
        // check if the admin exists before trying to edit it
        //$id=$_GET['idu'];
        $data['admin'] = $this->Admin_model->get_admin($id);
        
        if(isset($data['admin']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'nama' => $this->input->post('nama'),
                    'alamat' => $this->input->post('alamat'),
                    'pass' => $this->input->post('pass'),
                    'uname' => $this->input->post('uname'),
                    'class' => $this->input->post('class'),
                );

                $this->session->set_flashdata('announce', 'Berhasil Edit Data');
                $this->Admin_model->update_admin($id,$params);            
                redirect('admin/profile/'.$id);
                
               
            }
            else
            {

                $data['main_view'] = 'admin/edit';
                $this->load->view('template',$data);
            }
        }
        else
        {
            show_error('The admin you are trying to edit does not exist.');
        }
    } 

    function gantipass($id)
    {
       
         $data['admin'] = $this->Admin_model->get_admin($id);
         
         $pwbaru= $this->input->post('pwbaru');
         $lagi= $this->input->post('lagi');
        if(isset($data['admin']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   

                if($this->Admin_model->userCheck($id) == false) 
                        {       
                            $this->session->set_flashdata('announce', 'password Lama Salah');
                            redirect('admin/gantipass/'.$id);    
                        }
                else {
                            if ($pwbaru==$lagi) {
                                    $params = array(
                                          'pass' => $this->input->post('lagi'),
                                        );
                                    $this->session->set_flashdata('announce', 'Berhasil Edit Password');
                                    $this->Admin_model->gantipass($id,$params);            
                                    redirect('admin/profile/'.$id);     
                            }

                            else {
                                 $this->session->set_flashdata('announce', 'Password Harus Sama');
                                        redirect('admin/gantipass/'.$id);    
                            }
                    }
                }
            else
            {

                $data['main_view'] = 'admin/changepas';
                $this->load->view('template',$data);

            }
        }
        else
        {
            show_error('The admin you are trying to edit does not exist.');
        }
    }

    function profile($id)
    {
       
         $data['admin'] = $this->Admin_model->get_admin($id);
        $data['main_view'] = 'admin/profile';
        $this->load->view('template', $data);
    }
    /*
     * Deleting admin
     */
    function remove($id)
    {
        $admin = $this->Admin_model->get_admin($id);

        // check if the admin exists before trying to delete it
        if(isset($admin['id']))
        {
            $this->session->set_flashdata('announce', 'Berhasil Hapus Data');
            $this->Admin_model->delete_admin($id);
            redirect('admin/index');
        }
        else
            show_error('The admin you are trying to delete does not exist.');
    }

    function cari() {
       $data['admin']=$this->Admin_model->caridata();
       //jika data yang dicari tidak ada maka akan keluar informasi 
       //bahwa data yang dicari tidak ada
       if($data['admin']==null) {
          print 'maaf data yang anda cari tidak ada atau keywordnya salah';
          //print br(2);
          print anchor('admin','kembali');
           $this->load->view('errors/error');
          }
          else {
              $data['main_view'] = 'admin/index';
        $this->load->view('template', $data); 
            }
        }
    
}
