<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pelanggan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pelanggan_model');
        $this->load->helper('url');
       
        if($this->session->userdata('logged_in') == false)
        {
                redirect('login');
        }

    } 

    /*
     * Listing of pelanggan
     */
    function index()
    {
        $iu=$this->session->userdata('id');
        $set=$this->session->userdata('class');
        $data['pelanggan']=$this->Pelanggan_model->get_all_pelanggan($iu,$set);
        $data['main_view'] = 'pelanggan/index';
        $this->load->view('template', $data);
    }

    /*
     * Adding a new pelanggan
     */
    function add()
    {   
         //$data['pelanggan'] = $this->Pelanggan_model->get_pelanggan($id);
        $iu=$this->session->userdata('id');
        $data['admin'] = $this->Pelanggan_model->get_admin($iu);
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'id_admin' => $this->input->post('id'),
				'nama' => $this->input->post('nama'),
				'alamat' => $this->input->post('alamat'),
				'kd_tarif' => $this->input->post('kd_tarif'),
                'status' => $this->input->post('status'),

            );
            
           
            $this->session->set_flashdata('announce', 'Berhasil Tambah Data');
            $this->Pelanggan_model->add_pelanggan($params);
            redirect('pelanggan/index');
           
        }
        else
        {            
            
            $data['tarif']=$this->Pelanggan_model->tampiltarif();
            $data['main_view'] = 'pelanggan/add';
            $this->load->view('template', $data);
        }
    }  

    /*
     * Editing a pelanggan
     */
    function edit($id)
    {   
        // check if the pelanggan exists before trying to edit it
        $data['pelanggan'] = $this->Pelanggan_model->get_pelanggan($id);
        
        if(isset($data['pelanggan']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
					'alamat' => $this->input->post('alamat'),
					'kd_tarif' => $this->input->post('kd_tarif'),
                );
                $this->session->set_flashdata('announce', 'Berhasil Ubah Data');
                $this->Pelanggan_model->update_pelanggan($id,$params);            
                redirect('pelanggan/index');
            }
            else
            {
                
                $data['tarif']=$this->Pelanggan_model->tampiltarif();
                $data['main_view'] = 'pelanggan/edit';
                $this->load->view('template', $data);            }
        }
        else
            show_error('The pelanggan you are trying to edit does not exist.');
    } 

    /*
     * Deleting pelanggan
     */
    function remove($id)
    {
        $pelanggan = $this->Pelanggan_model->get_pelanggan($id);

        // check if the pelanggan exists before trying to delete it
        if(isset($pelanggan['id']))
        {
            $this->session->set_flashdata('announce', 'Berhasil Hapus Data');
            $this->Pelanggan_model->delete_pelanggan($id);
            redirect('pelanggan/index');
        }
        else
            show_error('The pelanggan you are trying to delete does not exist.');
    }

    function cari() {
        $iu=$this->session->userdata('id');
       $data['pelanggan']=$this->Pelanggan_model->caridata($iu);
       //jika data yang dicari tidak ada maka akan keluar informasi 
       //bahwa data yang dicari tidak ada
       if($data['pelanggan']==null) {
          print 'maaf data yang anda cari tidak ada atau keywordnya salah';
          //print br(2);
          print anchor('pelanggan','kembali');
           $this->load->view('errors/error');
          }
          else {
              $data['main_view'] = 'pelanggan/index';
        $this->load->view('template', $data); 
            }
        }
    
}
