<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

     function userCheck($id){
      
        $password=$this->input->post('pwlama');

        $kueri = $this->db->where('id',$id)->where('pass',$password)->get('admin');
        if($kueri->num_rows() > 0){
            return true;
        }
        else
        {
            return false;
        }
    }
    
    /*
     * Get admin by id
     */
    function get_admin($id)
    {
        return $this->db->get_where('admin',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all admin
     */
    function get_all_admin()
    {
        $this->db->order_by('id', 'desc');
        return $this->db
                    ->where('class','user')
                    ->select('a.id,a.nama,a.uname,a.pass,a.alamat,a.class,a.status')
                    ->get('admin a')->result_array();
    }
        
    /*
     * function to add new admin
     */
    function add_admin($params)
    {
        $this->db->insert('admin',$params);
        return $this->db->insert_id();
    }
     function add_pelanggan($params1)
    {
        $this->db->insert('pelanggan',$params1);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin
     */
    function update_admin($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('admin',$params);
    }

    function gantipass($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('admin',$params);
    }
    
    /*
     * function to delete admin
     */
    function delete_admin($id)
    {
        return $this->db->delete('admin',array('id'=>$id));
    }
    function caridata(){
    $c = $this->input->POST ('cari');
    $this->db->like('nama', $c);

    $query = $this->db->get ('admin');
    return $query->result_array(); 
 }
}
