<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pelanggan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pelanggan by id
     */
    function get_pelanggan($id)
    {
        return $this->db->get_where('pelanggan',array('id'=>$id))->row_array();
    }
    function get_admin($id)
    {
        return $this->db->get_where('admin',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all pelanggan
     */
    function tampiltarif()
    {
    return $this->db->get('tarif ')->result_array();
    }   

    function get_all_pelanggan($idu,$set)
    {
        $this->db->order_by('id', 'desc');
        
                    if($set=='admin1'){
       return $this->db
                    ->where('a.class','user')
                    ->where('p.status','Belum Ditagih')
                    ->select('p.id,p.nama,p.alamat,t.daya,t.kode,a.class')
                    ->join('tarif t','t.kode=p.kd_tarif')
                    ->join('admin a','p.id_admin=a.id')
                    ->get('pelanggan p')->result_array();
                }
                else{
                   return $this->db
                    ->where('id_admin',$idu)
                    ->where('status','Belum Ditagih')
                    ->select('p.id,p.nama,p.alamat,t.daya,t.kode')
                    ->join('tarif t','t.kode=p.kd_tarif')
                    ->get('pelanggan p')->result_array();
                }
    }
        
    /*
     * function to add new pelanggan
     */
    function add_pelanggan($params)
    {
        $this->db->insert('pelanggan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pelanggan
     */
    function update_pelanggan($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('pelanggan',$params);
    }
    
    /*
     * function to delete pelanggan
     */
    function delete_pelanggan($id)
    {
        return $this->db->delete('pelanggan',array('id'=>$id));
    }

    function caridata($idu){
    $c = $this->input->POST ('cari');
    $this->db->like('nama', $c);

    $query = $this->db
                    ->where('p.id_admin',$idu)
                    ->select('p.id,p.nama,p.alamat,t.daya,t.kode')
                    ->join('tarif t','t.kode=p.kd_tarif')
                    ->get('pelanggan p');
    return $query->result_array(); 
 }
}
