<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pembayaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pembayaran by id
     */
    function get_pembayaran($id)
    {
        return $this->db->get_where('pembayaran',array('id_tagihan'=>$id))->row_array();
    }
        
    /*
     * Get all pembayaran
     */
    function tampiltagihan()
    {
        return $this->db->get('tagihan')->result_array();
    }

    function idpelanggan($id)
    {
        
       
       
        $q= $this->db->select('id_pelanggan')->from('tagihan')->where('id',$id)->get();
        return $q->row()->id_pelanggan;
    

    }

    function get_all_pembayaran()
    {
        $ses=$this->session->userdata('id');
        $this->db->order_by('id', 'desc');
        if ($this->session->userdata('class')=='admin1') {
              return $this->db
                    ->where('a.class','user')
                    ->select('p.id ,p.tgl_bayar,pl.nama,p.jumlah_tagihan,p.biaya_denda,p.biaya_admin,p.status,p.id_tagihan,pl.id_admin')
                    ->join('tagihan t','p.id_tagihan=t.id')
                    ->join('pelanggan pl','pl.id=t.id_pelanggan')
                    ->join('admin a','a.id=pl.id_admin')
                    ->get('pembayaran p')->result_array();
        }
        else{
            return $this->db
             ->where('a.id',$ses)
                    ->select('p.id ,p.tgl_bayar,pl.nama,p.jumlah_tagihan,p.biaya_denda,p.biaya_admin,p.status,p.id_tagihan,pl.id_admin')
                    ->join('tagihan t','p.id_tagihan=t.id')
                    ->join('pelanggan pl','pl.id=t.id_pelanggan')
                    ->join('admin a','a.id=pl.id_admin')
                    ->get('pembayaran p')->result_array();
        }
      
    }
        
    /*
     * function to add new pembayaran
     */
    function add_pembayaran($params)
    {
        $this->db->insert('pembayaran',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pembayaran
     */
    function update_pembayaran($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('pembayaran',$params);
    }

    function update_pembayaran1($id,$params)
    {
        $this->db->where('id_tagihan',$id);
        //$this->db->delete('tagihan',array('id_pelanggan'=>$id));
        return $this->db->update('pembayaran',$params);
    }
    
    /*
     * function to delete pembayaran
     */
    function delete_pembayaran($id)
    {
        return $this->db->delete('pembayaran',array('id'=>$id));
    }

    function delete_pembayaran1($id)
    {
        return $this->db->delete('pembayaran',array('id_tagihan'=>$id));
    }

    function delete_pelanggan($id)
    {
        return $this->db->delete('pelanggan',array('id'=>$id));
    }

    function caridata(){
    $c = $this->input->POST ('cari');
    $this->db->like('nama', $c);

    $query = $this->db
                    ->select('p.id ,p.tgl_bayar,t.nama,p.jumlah_tagihan,p.biaya_denda,p.biaya_admin,p.status')
                    ->join('pelanggan t','p.id_tagihan=t.id')
                    ->get('pembayaran p');
    return $query->result_array(); 
 }
 

}
