<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tarif_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tarif by id
     */
    function get_tarif($id)
    {
        return $this->db->get_where('tarif',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tarif
     */
    function get_all_tarif()
    {
        $this->db->order_by('id', 'asc');
        return $this->db->get('tarif')->result();
    }
        
    /*
     * function to add new tarif
     */
    function add_tarif($params)
    {
        $this->db->insert('tarif',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tarif
     */
    function update_tarif($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tarif',$params);
    }
    
    function kodeauto()
    {
        return $this->db->selectmax('kode')->get('tarif')->result_array();
    }

    /*
     * function to delete tarif
     */
    function delete_tarif($id)
    {
        return $this->db->delete('tarif',array('id'=>$id));
    }
     function caridata()
     {
        $c = $this->input->POST ('cari');
        $this->db->like('kode', $c);

        $query = $this->db->get ('tarif');
        return $query->result(); 
     }

}
